#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro package install youtube-dl <args...>"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  which youtube-dl >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    pm install -y youtube-dl
  fi

  log::success "install youtube-dl success."
}

run() {
  core $@
}

run $@
